### ISSUE TITLE
Create component - Add Cohort Popup

### ISSUE THREAD

**Issue by lucianosimoni** [boolean-uk/team-dev-frontend-client#115]
### Create a {AddCohortPopup} component
It needs to have the absolute position, and have full width and heigth, with a background with a small amout of opacity to give the effect of a PopUp

## Requirements:
- Receives the prop: _setRenderCohortPopup_, which must be set to `false` when the popup is closed
- Store all the 3 values in a form to then be sent to within a JSON file:
```json
{
"cohortName": "Cohort 4",
"startDate": "2023-07-30T23:00:00.000Z",
"endDate": "2023-07-30T23:00:00.000Z" 
}
```
- The ID of the Cohort is automatic! No need to specify it
- Able to import images from the computer, and if not imported, use [DiceBear](https://avatars.dicebear.com/styles/initials) as an IMG (returns svg in the url) to pick a picture image (So it is not empty)
- Create the input to select Start Date. Can not select previous Time (Your cohort isn't capable of starting yesterday 🥴)
- Create the input to select End Date
- Name of the Cohort MUST be unique! the db does not accept non unique names for the cohorts
- - Create a logic to check for the existing cohorts names, comparing it to the typed value.
- - Data can be GET from end point: ``http://localhost:4000/cohorts``
- - - Check Insomnia Cohorts (Mixed) > Get All Cohorts (Anyone) for more details
- Data must be POST to the end point: ``http://localhost:4000/cohorts``

_**Check image to create the CSS layout**_
Could use `grid`. Optional. See best way as you code.

![Image](https://user-images.githubusercontent.com/71110718/203833912-acc3c037-f797-46a8-b114-0ea646217844.png)

**Comment by chris2733** [comment]
Looks good, small questions, how are you going to ensure the user cannot select a start date in the future and an end date in the past? Also how will you style the popup, with flex or grid? You could also use position:fixed for an overlay potentially.

**Comment by lucianosimoni** [comment]
Oh, fixed, nice idea.
