### ISSUE TITLE
Displaying Home Page - Grid

### ISSUE THREAD

**Issue by MattVwaves** [boolean-uk/team-dev-frontend-client#116]
****Requirements**

Create homepage as below using CSS grid.

**Implementation**

- Create grid-template with 3 columns: sidebars are fixed width and middle 1fr
- Further issues will deal with breaking down the layout further

- The code for the component will live in a ```PostPage.js ``` file in the folder: /src/components/posts
- All relevant styles will be added to the style.css in the same folder

![feed](https://user-images.githubusercontent.com/104565789/203780868-2cb0c5cf-9a94-41cd-bf7a-9ed577c3831b.png)

**Comment by dogezen** [comment]
OK - sounds good

Please coordinate with @lucianosimoni about the sidebar

The Header component is already done/exists for you, no need to re-create.

How will I know that the work is done? How far will you design the layout for: ie. as soon as the 3 column divs are done, this issue can be marked as done, or will you break the layout further than that?
