### ISSUE TITLE
Create component - Add Student Popup

### ISSUE THREAD

**Issue by OlhaDorofiychuk** [boolean-uk/team-dev-frontend-client#120]
### Create {AddStudentToCohortPopUp} component.

It needs to have the absolute position, and have full width and height, with a background with a small amount of opacity to give the effect of a PopUp

Requirements:

Students and setStudents should be passed as Props.

import client from './utils/client'. 
let response = client.get('/users') and render filtered response to include only students with no cohort assigned. 

example of response with student without cohort : 
```js
{
		"id":11,
		"cohortId":null,
		"role":"STUDENT",
		"firstName":"Test",
		"lastName":"Test",
		"email":"notmyrealemail@email.com",
		"biography":null,
		"githubUrl":null,
		"profileUrl":"https://images.unsplash.com/photo-1542652735873-fb2825bac6e2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
	},
```

- Select student and add this student to the cohort we are in onClick.
Add PATCH reques to the client as well.
OnClick send PATCH request via client and update students state with added cohort ID ('http://localhost:4000/users/id' )

- This only renders for teachers

![Image](https://user-images.githubusercontent.com/112890664/203837507-6732e658-9f80-4959-b235-f2927d430810.jpg)

**Comment by Auenc** [comment]
> Send fetch('http://localhost:4000/users' )

We don't use `fetch` in the codebase, as we have the `utils/client.js` file that we use to make requests. It would be a good idea to update the issue to reflect this, so when someone comes to do the work they know what code to use.

It would be nice if you formatted the snippet.

**Comment by chris2733** [comment]
Also if you are already showing which parts of the popup mockup are using which html element (<header>) you should list what the other parts are using too, like ul, li etc for consistency
