### ISSUE TITLE
Filling out details of ProfilePage

### ISSUE THREAD

**Issue by Dex491** [boolean-uk/team-dev-frontend-client#121]
### Creating grid for the page layout, see below image for an example:
![image](https://user-images.githubusercontent.com/111896393/203817470-29920448-bb88-45ea-bafe-1822a4d8e99b.png)

### Wireframe that we're following
![Profile Page](https://user-images.githubusercontent.com/111896393/203839071-32595ff5-8cc3-4d8e-baf6-c45622ad8101.jpg)

### Inserting elements into the grid
- Within each div will be a header (Basic Info, Training Info, Contact Info, Bio), a ul containing lis for each data display (firstname, last name etc.)
- Each piece of data will be accessed through the currentUser state 
	- for example `currentUser.firstName` for the first name, `currentUser.biography` to see their bio etc.
	- see below `console.log(currentUser)`
![image](https://user-images.githubusercontent.com/111896393/203838349-c5faacdc-86c8-4b2f-ba5f-e29fedf2faa1.png)

**Comment by Auenc** [comment]
This needs more detail. 
> Within each div will be a header (Basic Info, Training Info, Contact Info, Bio), a ul containing lis for each data display (firstname, last name etc.)

Can you add a wireframe for each of the sections? Or, if they are done in other tickets, link to those tickets in here so it's easily accessible. 

> Each piece of data will be accessed through the currentUser state

Can you add more detail in regards to what data will be accessed through the `currentUser`? What data will be passed to what component?

**Comment by chris2733** [comment]
Nice wireframe! Can you add a snippet of what data will be accessed through currentUser? Also in the 'contact info' section of the wireframe, if you are adding <data.email> to one section, be sure to add the rest for consistency

**Comment by chris2733** [comment]
Loosk good!
