### ISSUE TITLE
Create component - Navigation Rail

### ISSUE THREAD

**Issue by lucianosimoni** [boolean-uk/team-dev-frontend-client#123]
# Component Name: _NavigationRail_
_Create it in a folder with same name under `components`_

# Where it will be used
~~In all of the pages of the project, as a reusable component.~~
In the _App.js_, so it will always show in all pages.

***

# Requirements:

Must receive as a prop `loggedInUser` from the component calling it
```jsx
<NavigationRail user={ loggedInUser } />
```

_How is received by the component:_
```js
function NavigationRail ({ user }) {....
```

Have 3 fixed Buttons (Home, Profile, Cohort)
- Home (Which is the `Posts` page)
- - navigate to `/posts`
- Profile
- - navigate to `/profile/${user.id}`
- - the `user` needs to be 
Conditional of Cohort Button
- Cohort
- - IF TEACHER:
- - - navigate to `/cohorts`
- - IF STUDENT
- - - navigate to `/cohorts/${user.cohortId}`

Use the `Google Icons` as icons.

~~Have 2 conditional Buttons that are rendered only if User is a teacher~~
~~_Check for the prop `user` and render only if role is TEACHER_~~
~~- Notes~~
~~- - Link to `/notes/${user.id}`~~
~~- Logs~~
~~- - Link to `/logs/${user.id}`~~

No need for the _Notes_ and _Logs_ for the moment.

~~> Create `notes` and `logs` placeholder pages~~

### Create Routes for the Links
_Notes_ and _Logs_ also does not have a Route setup in the `App.js`
URLs:
- `/logs/:teacherId`
- `/notes/:teacherId`

***

_Possible `jsx` structure:_
```jsx
<li className="nav-item-panel">
    <div className="icon-circle">
        <span className="material-symbols-outlined">home</span>
    </div>

    <span className="nav-item-name">Home</span>
</li>
```
_`.nav-item-panel` could work with `display:flex` `flex-direction:column`, to avoid use of grid_

***

![Image](https://user-images.githubusercontent.com/71110718/203835563-5afb0064-7288-4f72-ad32-e68ae81c5c56.png)

**Comment by chris2733** [comment]
Looks great! Well broken down
