### ISSUE TITLE
Create EditProfile component

### ISSUE THREAD

**Issue by Joelzor** [boolean-uk/team-dev-frontend-client#130]
### Create EditProfile.js component in profiles folder

- Reuse grid structure from ProfilePage - obviously don't include edit button
- Add text inputs for each property with corresponding labels
- Don't worry about styling too much for now 
- requesting user data will be done in a separate issue
- Add temp cancel and save buttons in bottom right
- Radio buttons or dropdown select for role to ensure only 'teacher' or 'student' selected

### Create route in App.js

- For now, wrap in AuthenticateUser function
- Path should be `/profile/:id/edit`

### Wireframe we're following:
![203285548-c4ff0c1d-3034-48b2-a58e-40a88377873b](https://user-images.githubusercontent.com/111896393/204251207-92d53ba6-ddeb-4ee9-953a-6f5d98e20432.png)

**Comment by chris2733** [comment]
Looks good, for a wireframe you said you are reusing the one from ProfilePage it would be a good idea to link it to this issue
