### ISSUE TITLE
Set up ProfileEdit form control

### ISSUE THREAD

**Issue by Joelzor** [boolean-uk/team-dev-frontend-client#131]
### Set up state values

- Similar to ProfilePage, set up `[currentUser, setCurrentUser]` as a state value
- Set up useEffect and make get request with the id parameter in url (exactly the same as in ProfilePage) 
- Set the state user to the returned data

### Form control

- Set value of each form input to be the corresponding property from currentUser state value - eg. `value={currentUser.firstName}`
- Set up handleChange and handleSubmit functions
- In handleChange, we update the values of the currentUser - check which input name has been edited then update currentUser with that value
- Make a PATCH request in handleSubmit function - /users/update/{id} (not sure how this will work with the client methods (client.get etc))
- useNavigate to redirect user back to ProfilePage component - fetch will run again with the updated data

**Comment by chris2733** [comment]
If you are using the same currentUser and the same fetch, ie it is the same data it would be wiser to pass this data down to this component - only if this is possible with your current structure. Ideally you want to just work from the one user state, and not fetch multiple times unnecessarily.

**Comment by Joelzor** [comment]
We considered that but in that way, if the user was to directly access for example, profiles/2/edit in the URL bar, we wouldn't have the data no? I can't imagine many people would do that, but still ;)

**Comment by chris2733** [comment]
Not sure on your current structure, but if ProfileEdit is within ProfilePage you would just pass the prop down to the component, so would have access to the data

**Comment by Joelzor** [comment]
Is it possible to add these issues to the todo list? Could we maybe add fetch in both then try to refactor later if possible?

**Comment by chris2733** [comment]
Sure thing, just remember if you are trying to fetch exactly the same thing then you should try to find a way of only doing it once, then passing the data wherever you need :)

**Comment by Joelzor** [comment]
We'll try to make that work, thank you :) :)
