### ISSUE TITLE
Add loading spinner to ProfilePage + EditProfile

### ISSUE THREAD

**Issue by Joelzor** [boolean-uk/team-dev-frontend-client#132]
### Add loading spinner

- Find a good loading spinner online 
- Set up loading state in the two components - check TODOs in code (added in branch for issue 121)
- Loading will initially be true, then once the data is fetched we set it to false
- Return loading spinner when loading is true

**Comment by chris2733** [comment]
Looks good!

**Comment by Logi13** [comment]
Looks good to me!
