### ISSUE TITLE
Remove unused temporaryAddPopup var from CohortsList

### ISSUE THREAD

**Issue by lucianosimoni** [boolean-uk/team-dev-frontend-client#160]
```
src/components/cohortsList/CohortsList.js
  Line 20:9:  'temporaryAddPopup' is assigned a value but never used  no-unused-vars
```

It was a temporary var, done just for a placeholder of issue #115

**Comment by chris2733** [comment]
Might want to add a bit more information to make it look a bit more a official.. Maybe explain briefly why it was no longer being used
