### ISSUE TITLE
Create edit and delete buttons on posts and implement logic

### ISSUE THREAD

**Issue by MattVwaves** [boolean-uk/team-dev-frontend-client#164]
**Requirements**

- If user is a teacher they can edit or delete posts
- If a user is a student they can only edit or delete their own posts

**Implementation**

- The edit and delete buttons will be added in the ```post``` component and will be conditionally rendered according to the role of the user who is logged in/created the post
- A route will be made for an `edit` component with the path `/posts/:id/edit` and the `edit` button will be encapsulated in an appropriate link
- In the `edit` component will be a form displaying the current post content as a placeholder
- A `submit` button will be present, which when clicked will create a PATCH request and the user will be taken back to the post feed via `navigate`
- On clicking the `delete` button  DELETE request will be made for that post and the user will be taken back to the post feed via `navigate`

**Comment by chris2733** [comment]
Looks good, if anything I'd be nit-picky and want the start of the sentences to be capitalised...
