### ISSUE TITLE
CSS changes (makeover) for ProfilePage

### ISSUE THREAD

**Issue by Joelzor** [boolean-uk/team-dev-frontend-client#165]
### Fresh makeover for profile page

- Move 'Profile' heading to left hand side, add some margin below and above
- Add space between profile photo and name
- Increase space between li elements

### Add colored tags for each label 

For each label (First Name: etc), we want to add a background colour and a slight border radius (10 - 15px). We'll use the provided colour palate for the background colour: 

![image](https://user-images.githubusercontent.com/37843920/204576805-af5ecbc6-cc1e-4dd3-b8af-adcf3b1dc1a0.png)

We'll probably use Neutral Blue 3 / 4 for the background of the labels, depending on some slight experimentation. The colour will be set to black or another dark colour for the contrast

**Comment by chris2733** [comment]
Lovely colours. To nit pick you could state in px the spaces changes, but otherwise clear
