### ISSUE TITLE
Create component -MyExercises for student cohorts page

### ISSUE THREAD

**Issue by Haroogle** [boolean-uk/team-dev-frontend-client#168]
### Create component to show exercises set for a cohort

-Create and set state for exercises using ```client.get('/cohorts/:id/cohortExercises')```
-Map state showing an item for each exercise's name and a link to its github page
-CSS used for styling and grid

![Image](https://user-images.githubusercontent.com/111692114/204597898-058ef9ba-b41a-4cd7-9c68-4edd62aefd09.jpg)

**Comment by chris2733** [comment]
Looks good!
