### ISSUE TITLE
Update style from CohortsPage, and a couple of JSX

### ISSUE THREAD

**Issue by lucianosimoni** [boolean-uk/team-dev-frontend-client#172]
CSS must be updated and the JSX must implement the _StudentsList_ component

### Remarks
- grid not working 
- Check for all the classes in the `style.css` and remove unused.
- Use spaces and extensively use `class names` for all of the components.
- - It requires some changes in the `jsx` of the component using it (Teachers or Student)
- Make sure to use all the available width of the page.
- `BUG:` the width of the <main> should not be `100vh` (viewport Height), instead should be `100vw` (viewport width)
- 

### Do not use elements callouts like `li` or `nav`. Use nested `className` like `.list-wrapper .list-item`
It avoids problems with other pages receiving those styles by mistake.

![Image](https://user-images.githubusercontent.com/71110718/204630481-46ec64d5-a3d5-4d16-a4fd-a5ba4544a1ce.png)

**Comment by dogezen** [comment]
OK looks good, please proceed with this
