### ISSUE TITLE
Various small fixes on posts-page

### ISSUE THREAD

**Issue by MattVwaves** [boolean-uk/team-dev-frontend-client#191]
- remove bullets from list in the `posts-page` css file
- remove left column from grid no longer needed
- display time of post in a more readable way/remove excess data
            e.g. 12.12.22 - 08:30 _or_ Mon 12th Dec 2022 - 08.30

![styling](https://user-images.githubusercontent.com/104565789/205039185-47df7eda-3fd5-477e-b45c-9ee70cbf6b1a.png)

**Comment by dogezen** [comment]
1 - for removing bullets, which css file should I put that in?
3 - time display, how would the time format be? ie "Tue 10th Dec 2022 - 8.30am" or..?

**Comment by MattVwaves** [comment]
for the time I personally like something more concise but could I not leave it open like that in case it had to be changed later?
