### ISSUE TITLE
Moving search bar from header to main in SearchResults

### ISSUE THREAD

**Issue by Dex491** [boolean-uk/team-dev-frontend-client#193]
### Dependant on #190 
- In the `SearchResults` page there will be no search bar in the header, and instead it is within the main
	- Conditional rendering to check- we pass a prop into the Header- `searchBarVisible=true` - we'll set it to false in the SearchResults component and not display it 
	- This will be just for aesthetic purposes so there's not 2 search bars in `SearchResults`

**Comment by dogezen** [comment]
Might be better to pass a `props` to <Header> specifying whether or not to show the search bar!

```js
function Header({searchBarVisible=true})
```

Make it true by default
