### ISSUE TITLE
Creating a component for each individual result in SearchResults

### ISSUE THREAD

**Issue by Dex491** [boolean-uk/team-dev-frontend-client#194]
### Create a component for each individual result:
- Create the `SearchResult` component in the Search folder
	- Pass down `loggedInUser` so we know what buttons to display (based on role)
	- Map through the filtered results mentioned in #192 and pass in the whole object
	- De-structure the object to get the `firstName`, `lastName`, `profileUrl` and `cohortId` 
- conditional rendering based on user role for the extra buttons
	- pass individual data, cohort data and logged in user into component
	- when searching for people, if the user is a student, the cohort button should be replaced with text if they're in a different cohort to the user
- fill out fields with results pulled from the database

### See below wireframe for reference:
![image](https://user-images.githubusercontent.com/111896393/205042957-026ef038-a0fe-402a-9d81-d5afca9131cc.png)

**Comment by dogezen** [comment]
What is the component name? Where should the file be created? What props should be passed down exactly?
