### ISSUE TITLE
Placeholder for while results are being fetched.

### ISSUE THREAD

**Issue by wagnerAJS221** [boolean-uk/team-dev-frontend-client#195]
### Loading spinner things in SearchResults.js

- Placeholder for while results are being fetched:
    - New state value - `searching, setSearching` = initially set to true 
    - if the state is equal to true, return "Searching..." and nothing else- possible loading spinner later
    - When the results are fetched, set searching to false
    - When false, we display the normal page with the results

**Comment by dogezen** [comment]
Not sure:
1. in what component / file this logic needs to be present
2. you mention state is null, which state exactly?
