### ISSUE TITLE
Teacher Can Add an Exercise to a Cohort

### ISSUE THREAD

**Issue by glowkeeper** [boolean-uk/team-dev-frontend-client#2]

**Comment by mbalabanov** [comment]
![Image](https://user-images.githubusercontent.com/3449511/196142800-43e6f675-d5cb-4706-b6b4-a107c49f155f.png)

**Comment by glowkeeper** [comment]
See issue #56 - docs in place and backend API verified. _If_ there was time, this could be actioned...
