### ISSUE TITLE
Add functionality to CohortListItem

### ISSUE THREAD

**Issue by lucianosimoni** [boolean-uk/team-dev-frontend-client#217]
When the user press on the component _CohortListItem_ (rendered inside _CohortsList_), the user should be redirected to the page of that specific cohort.

### Todo:
On the _CohortListItem.js_, add a `onClick` atribute to the _<div>_ element. And on click (thought `useNavigate` imported) navigate to `/cohorts/${cohort.id}`.
Cohort is the prop received by the component. Access its ID (may be cohortId, so check).

**Comment by Auenc** [comment]
Sounds good to me!
