### ISSUE TITLE
Add header to CohortsStudentsPage

### ISSUE THREAD

**Issue by OlhaDorofiychuk** [boolean-uk/team-dev-frontend-client#218]
Just add missing header to Cohort Students Page

**Comment by Auenc** [comment]
Is this a header component? Or JSX for a header?

**Comment by OlhaDorofiychuk** [comment]
component itself

**Comment by Auenc** [comment]
Sorry - is the missing header a Header component? Or is it some HTML that you need to write?

**Comment by OlhaDorofiychuk** [comment]
header from the main page

**Comment by OlhaDorofiychuk** [comment]
Header component

**Comment by Auenc** [comment]
Okay cool, sounds good to me!

**Comment by OlhaDorofiychuk** [comment]
thanks
