### ISSUE TITLE
API-Issue: Endpoint for changing user roles missing (e.g. student to teacher)

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#23]
Teachers can create a new user with the existing API endpoint. The new user always has the role "Student" by default.

Teachers should be able to change the role of a created user. The API endpoint is not listed in the API documentation at https://boolean-uk.github.io/team-dev-frontend-server/#tag/user

**Comment by glowkeeper** [comment]
I _think_ you just need to add the property `role: 'TEACHER'` to the _create a new user API endpoint_. Can you test, please?
