### ISSUE TITLE
API-Issue: Purpose of Notes unclear 

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#24]
The API documentation provides an endpoint for Notes. The response provides a string with the note text and a teacher ID and a student ID.

The project team is uncertain what the purpose of notes is. Are they related to an exercise a student has submitted or a post or something else?

**Comment by glowkeeper** [comment]
Looking at the ERD, it looks as though the intention is to relate _Notes_ to users - i.e. _Marin is an excellent dev who will make a fabulous addition to any team_

**Comment by mbalabanov** [comment]
Dear Project Manager, what is the priority of this feature and how does it fit into the requirements as outlined on Monday by our team?
(Please see the UI you signed off on here: https://discord.com/channels/811981269595324436/961603225398677514/1029040516182048858 )

**Comment by mbalabanov** [comment]
Dear project manager, please kindly provide guidance on the requirements for notes in the frontend.
Are notes only relevant for the teacher view (i.e. as an evaluation for a student)?
Or should students also be able to see the notes?

**Comment by glowkeeper** [comment]
Notes are indeed only relevant for the Teacher view

**Comment by glowkeeper** [comment]
API verified to work and docs validated
