### ISSUE TITLE
Within the post date, display 'today' or 'yesterday' (+ time) if applicable

### ISSUE THREAD

**Issue by MattVwaves** [boolean-uk/team-dev-frontend-client#242]
**Requirements**

- If a post was made today then display e.g. `today at 12.45` 
- If a post was made yesterday then display e.g. `yesterday at 12.45` 

**Implementation**

- Use `date-fns` to extract today's date, yesterday's date and the date of the post:

`const today = format(new Date(), 'MMMM d')`
`const yesterday = isYesterday(new Date(today)`
`const postDay = format(parseISO(post.createdAt), 'MMMM d')`

- Extract the time of the post in a similar fashion and interpolate `today` /`yesterday` with `at (time)`
- Use a condition to check whether it is today or tomorrow and if not return the current date logic

**Comment by Logi13** [comment]
Just a note on this: With the format in this post it will display Month day -> today will be `December 5`, yesterday will be `December 4` so it will not be in the format shown in the example. I would suggest to add an accurate example on how the day will look like or update the format. You can see the formats in the documentation of date-fns: https://date-fns.org/v2.29.3/docs/format

**Comment by MattVwaves** [comment]
to be clearer I mean I'm checking `today` and `yesterday` with `postDay`
