### ISSUE TITLE
Implementing Initial Box Component into relevant components

### ISSUE THREAD

**Issue by akibria12** [boolean-uk/team-dev-frontend-client#243]
## Requirements ##

- Initial Box component needs to be called in these following components to function accordingly.

    - Comments.js
    - CommmnetsList.js
    - Post.js
    - PostForms.js

 ## Implementation ##

Using the Component named InitialBox; by calling in respective components to show the users initial as example - 'AA'
in a circle the component will be called in JSX as below example:

```
        <div className="comment-profile-img">
          <InitialBox/>
        </div>

**Comment by Auenc** [comment]
Looks good to me!
