### ISSUE TITLE
Bug - app breaks when adding new post

### ISSUE THREAD

**Issue by MattVwaves** [boolean-uk/team-dev-frontend-client#249]
When adding a new post the following error appears:

![length error](https://user-images.githubusercontent.com/104565789/205694703-b8658424-c65f-4513-a8a3-a80ecb6454c8.png)

To fix the bug the `commentsList` code needs to be reviewed, probably with console logs to determine the cause.

**Comment by Auenc** [comment]
The cause will likely be that you're using data somewhere without checking if that data exists. 

Added a null check in `CommentList` will likely be the fix!
