### ISSUE TITLE
API-Issue: Which data does the POST request to Create New Cohort need? 

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#37]
The API documentation for "Create Cohort" does not provide the information about the JSON payload required in the POST request.

An empty POST returns the error that "cohortName" must be a string.
Adding `{ "cohortName": "December Cohort" }` to the JSON request returns a DB error.

A new cohort should need a name, a start date and a duration.

**Comment by glowkeeper** [comment]
I'll take a look first thing

**Comment by glowkeeper** [comment]
You can create a cohort - you need to POST to the /cohort endpoint with the following (example) payload:

"cohortName=Cohort 1&startDate='01/02/2022'&endDate='01/05/2023'"

I'll check out what the docs say and amend accordingly (if necessary)

**Comment by glowkeeper** [comment]
Yup - it was just meant as an example - docs have been updated - please confirm...

**Comment by mbalabanov** [comment]
I cannot confirm that this works.

Please see the following video recording (HIDDEN video on Youtube): https://youtu.be/YawSvV22Ltw 

This HIDDEN video shows the REST Client in VSCode doing the following:
1. Login with a user to get a bearer token

2. API Documentation for cohort endpoint

3. API POST to cohort with the payload structure from API Documentation (which doesn't make sense)
{
  "status": "any string",
  "data": {
    "cohort": {
  "cohortName": "December Cohort",
  "startDate": "12/10/2022",
  "endDate": "15/01/2023"
    }
  }
}
**Result: FAIL**

4. API POST to cohort with a more common sense payload structure:
{
  "cohortName": "December Cohort",
  "startDate": "12/10/2022",
  "endDate": "15/01/2023"
 }
**Result: DIFFERENT FAIL**

**Comment by mbalabanov** [comment]
Resolved now after multiple messages on Discord.

Screenshot of first adaptation of API documentation for this request type done containing wrong information at the time: https://imgur.com/a/WdR1B5P 

Screenshot of second adaptation of the API documentation for this request type again containing wrong information: https://imgur.com/a/2ThkIfB

Closing issue.
