### ISSUE TITLE
API-Issue: When patching the user data through the API endpoint for user updates, the key githubUrl is not being updated

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#43]
When patching the user data through the API endpoint for user updates, the key `githubUrl` is not being updated.

A **possible but unverified** cause for this could be a typo in the API source code in the file `openapi.yml` line 1368 where `github_url` is used instead of `githubUrl` like everywhere else in the API source code.

**Comment by glowkeeper** [comment]
Hmmmm - line 1368 is not the issue, and I can't see anything obvious - could you give me the URL to which you're patching and some example data, please - that way I can have a closer look...

**Comment by glowkeeper** [comment]
Duplicate #36

**Comment by glowkeeper** [comment]
...ah - I can see some data in #36 - thanks - I'll use that and get back to you...
