### ISSUE TITLE
API-Issue: Add endpoints for cohorts

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#53]
At present, the API documentation only describes an endpoint to create a new cohort.

![image](https://user-images.githubusercontent.com/3449511/195645469-999b957c-a1be-48a0-a076-375b5d22d14e.png)

Please add API endpoints for cohort - only if user has role teacher:

- GET all cohorts
- PATCH one cohort by ID
- DELETE one cohort by ID

**Comment by glowkeeper** [comment]
https://boolean-uk.github.io/team-dev-frontend-server/#tag/cohort/operation/getAllCohorts
