### ISSUE TITLE
API-Issue: Log Endpoint needs documentation and a description of its purpose

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#54]
At present there is one API endpoint for log: create new log.

Steve stated during our call that the log endpoint is for internal DB logs. This does not match the ERD on the server side. There the log is called "deliverLog" and has a relationship to "Exercise" and "deliveryLogLine". Please see attached screenshot of relevant section in ERD.
![image](https://user-images.githubusercontent.com/3449511/195646445-7a715e9f-21f5-4f29-a459-50ce26c1510a.png)

What is the log? If we need to implement some frontend functionality, then we will need more than the endpoint for "create log", e.g. GET all logs, GET one log by ID, PATCH one log by ID, DELETE one log by ID - all only for role "TEACHER".

Please provide details on the requirements related to log and the priority of the implementation.

**Comment by glowkeeper** [comment]
On closer inspection, it looks like it is a log of delivered exercises per student. I suspect this can wait...

**Comment by glowkeeper** [comment]
This can wait
