### ISSUE TITLE
API-Issue: Add documentation for exercise endpoint and perhaps cohortExercise

### ISSUE THREAD

**Issue by mbalabanov** [boolean-uk/team-dev-frontend-client#56]
The ERD on the server side shows two entities related to exercises: "Exercise" and "CohortExercise.
![image](https://user-images.githubusercontent.com/3449511/195648227-56a4c34d-183e-43f2-a904-970fa511e6b7.png)

So far, the API documentation does not show any endpoint for "exercise" or "cohortexercise".
![image](https://user-images.githubusercontent.com/3449511/195647937-fd22b545-5406-4421-b867-89ec67ad7c81.png)

What is the purpose and what are the related requirements for the use of these entities on the frontend?

**Comment by glowkeeper** [comment]
The API endpoints are there - I'll try and find time to add the docs tomorrow morning...

**Comment by mbalabanov** [comment]
Please also provide guidance on the requirements related to these endpoints. What is the purpose of an exercise as opposed to a cohortexercise? What are the requirements for the frontend?

**Comment by glowkeeper** [comment]
_CohortExercise_ is a join table that decomposes a [many-to-many](https://en.wikipedia.org/wiki/Many-to-many_(data_model)) relationship, whereby a Cohort performs many exercises and an exercise has many cohorts.

I suppose the requirement for the frontend app' is the ability to add exercises and the ability to add those exercises to cohorts.

**Comment by mbalabanov** [comment]
![Screen Shot 2022-10-17 at 12 29 43](https://user-images.githubusercontent.com/3449511/196195067-73ba0518-103e-426e-a728-dc9ab53552d7.png)

**Comment by glowkeeper** [comment]
Added exercise and cohort exercise docs: https://boolean-uk.github.io/team-dev-frontend-server/#tag/exercise, and verified API - all ready to go...
