### ISSUE TITLE
A Teacher Can Create Notes About Students

### ISSUE THREAD

**Issue by glowkeeper** [boolean-uk/team-dev-frontend-client#59]

**Comment by mbalabanov** [comment]
What are the requirements for this in the frontend? Should notes be visible to the student or is this an internal note about a student that is only visible to another teacher?

**Comment by glowkeeper** [comment]
Only visible to teachers

**Comment by mbalabanov** [comment]
Dear project manager, you have assigned this ticket to me without any heads-up. We have never discussed the high-level requirements for this feature. There might be more aspects to the requirements of this feature than described above.

Please find below UI sketches for three variants with different advantages and disadvantages. Please keep in mind that according to the API documentation a student can only have one note associated with their ID. **Please kindly let us know which one meets the requirements for feature set and time for implementation best.**

The first sketch shows the most literal variant for this feature based on your sparse requirement description. This can be implemented the fastest:
![Notes-Option-1](https://user-images.githubusercontent.com/3449511/196298557-187aadbd-7595-4b9c-a2da-687dd4d6a2da.png)

The second sketch is slightly more user-friendly. This will take slightly longer to implement than the first variant:
![Notes-Option-2](https://user-images.githubusercontent.com/3449511/196298612-71fdbf32-ab46-46ed-9e31-5b22925c1358.png)

The third sketch is no longer solely based on your feature description above. It includes a list of all students, shows their related note and provides not only the option to add a new note but also to edit or delete existing notes. This will take the longest to implement:
![Notes-Option-3](https://user-images.githubusercontent.com/3449511/196298669-27052408-2d65-433e-be64-6553876df129.png)

**Comment by glowkeeper** [comment]
I reckon there are some fantastic designs there, and in particular, I really like option 3. My concern there is how does it show multiple notes for each student? And also _time_. I'm happy to discuss both of those issues, but basically, if you think you can achieve this before Friday easily enough, then go for it...

Meanwhile, I've added something about teacher notes to the [requirements](https://github.com/boolean-uk/team-dev-frontend-client/blob/main/docs/requirements.md#teacher-view-student-user-notes).

**Comment by mbalabanov** [comment]
Dear project manager, your response does not provide the guidance asked for in my question. The main question was, which of the three options should be implemented given the amount of time left? This is a matter of priority.
Option 3 will take the longest to implement at the cost of potentially missing out on core features that might have a higher priority like the **exercises** view for teachers.
I would like to kindly reiterate my request for guidance from you as a project manager.

**Comment by glowkeeper** [comment]
Apologies if my response wasn't clear - I like option 3 (as long as there's time).

**Comment by glowkeeper** [comment]
option 2 agreed on a call
